// <auto-generated />
using System;
using AutoSchool.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoSchool.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260420110629_SeedMoreQuestions")]
    partial class SeedMoreQuestions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutoSchool.Models.AnswerOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("AnswerOptions");

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            IsCorrect = true,
                            QuestionId = 101,
                            Text = "Зелёный"
                        },
                        new
                        {
                            Id = 1002,
                            IsCorrect = false,
                            QuestionId = 101,
                            Text = "Красный"
                        },
                        new
                        {
                            Id = 1003,
                            IsCorrect = false,
                            QuestionId = 101,
                            Text = "Жёлтый"
                        },
                        new
                        {
                            Id = 1004,
                            IsCorrect = true,
                            QuestionId = 102,
                            Text = "Запрещено, кроме случаев когда остановка невозможна"
                        },
                        new
                        {
                            Id = 1005,
                            IsCorrect = false,
                            QuestionId = 102,
                            Text = "Разрешено всегда"
                        },
                        new
                        {
                            Id = 1006,
                            IsCorrect = false,
                            QuestionId = 102,
                            Text = "Разрешено только направо"
                        },
                        new
                        {
                            Id = 1007,
                            IsCorrect = true,
                            QuestionId = 103,
                            Text = "Нужно уступить транспортным средствам на пересекаемой дороге"
                        },
                        new
                        {
                            Id = 1008,
                            IsCorrect = false,
                            QuestionId = 103,
                            Text = "Движение запрещено"
                        },
                        new
                        {
                            Id = 1009,
                            IsCorrect = false,
                            QuestionId = 103,
                            Text = "Вы на главной дороге"
                        },
                        new
                        {
                            Id = 1010,
                            IsCorrect = true,
                            QuestionId = 104,
                            Text = "60 км/ч"
                        },
                        new
                        {
                            Id = 1011,
                            IsCorrect = false,
                            QuestionId = 104,
                            Text = "90 км/ч"
                        },
                        new
                        {
                            Id = 1012,
                            IsCorrect = false,
                            QuestionId = 104,
                            Text = "40 км/ч"
                        },
                        new
                        {
                            Id = 1013,
                            IsCorrect = true,
                            QuestionId = 105,
                            Text = "Да, если предусмотрены конструкцией"
                        },
                        new
                        {
                            Id = 1014,
                            IsCorrect = false,
                            QuestionId = 105,
                            Text = "Только водитель"
                        },
                        new
                        {
                            Id = 1015,
                            IsCorrect = false,
                            QuestionId = 105,
                            Text = "Только на трассе"
                        },
                        new
                        {
                            Id = 1016,
                            IsCorrect = true,
                            QuestionId = 106,
                            Text = "Нет, запрещена"
                        },
                        new
                        {
                            Id = 1017,
                            IsCorrect = false,
                            QuestionId = 106,
                            Text = "Да, если нет пешеходов"
                        },
                        new
                        {
                            Id = 1018,
                            IsCorrect = false,
                            QuestionId = 106,
                            Text = "Да, не более 1 минуты"
                        },
                        new
                        {
                            Id = 1019,
                            IsCorrect = true,
                            QuestionId = 107,
                            Text = "Да, запрещена"
                        },
                        new
                        {
                            Id = 1020,
                            IsCorrect = false,
                            QuestionId = 107,
                            Text = "Нет, разрешена"
                        },
                        new
                        {
                            Id = 1021,
                            IsCorrect = false,
                            QuestionId = 107,
                            Text = "Запрещена только после перехода"
                        },
                        new
                        {
                            Id = 1022,
                            IsCorrect = true,
                            QuestionId = 108,
                            Text = "Перед стоп-линией"
                        },
                        new
                        {
                            Id = 1023,
                            IsCorrect = false,
                            QuestionId = 108,
                            Text = "На стоп-линии"
                        },
                        new
                        {
                            Id = 1024,
                            IsCorrect = false,
                            QuestionId = 108,
                            Text = "После стоп-линии"
                        },
                        new
                        {
                            Id = 1025,
                            IsCorrect = true,
                            QuestionId = 201,
                            Text = "Въезд запрещён в данном направлении"
                        },
                        new
                        {
                            Id = 1026,
                            IsCorrect = false,
                            QuestionId = 201,
                            Text = "Движение запрещено для всех"
                        },
                        new
                        {
                            Id = 1027,
                            IsCorrect = false,
                            QuestionId = 201,
                            Text = "Остановка запрещена"
                        },
                        new
                        {
                            Id = 1028,
                            IsCorrect = true,
                            QuestionId = 202,
                            Text = "Транспортное средство справа"
                        },
                        new
                        {
                            Id = 1029,
                            IsCorrect = false,
                            QuestionId = 202,
                            Text = "Транспортное средство слева"
                        },
                        new
                        {
                            Id = 1030,
                            IsCorrect = false,
                            QuestionId = 202,
                            Text = "Тот, кто едет быстрее"
                        },
                        new
                        {
                            Id = 1031,
                            IsCorrect = true,
                            QuestionId = 203,
                            Text = "Запрещено"
                        },
                        new
                        {
                            Id = 1032,
                            IsCorrect = false,
                            QuestionId = 203,
                            Text = "Разрешено"
                        },
                        new
                        {
                            Id = 1033,
                            IsCorrect = false,
                            QuestionId = 203,
                            Text = "Разрешено только в пробке"
                        },
                        new
                        {
                            Id = 1034,
                            IsCorrect = true,
                            QuestionId = 204,
                            Text = "Водительское удостоверение соответствующей категории"
                        },
                        new
                        {
                            Id = 1035,
                            IsCorrect = false,
                            QuestionId = 204,
                            Text = "Паспорт"
                        },
                        new
                        {
                            Id = 1036,
                            IsCorrect = false,
                            QuestionId = 204,
                            Text = "Свидетельство о рождении"
                        },
                        new
                        {
                            Id = 1037,
                            IsCorrect = true,
                            QuestionId = 205,
                            Text = "ДХО или ближний свет фар"
                        },
                        new
                        {
                            Id = 1038,
                            IsCorrect = false,
                            QuestionId = 205,
                            Text = "Только дальний свет"
                        },
                        new
                        {
                            Id = 1039,
                            IsCorrect = false,
                            QuestionId = 205,
                            Text = "Только противотуманные фары"
                        },
                        new
                        {
                            Id = 1040,
                            IsCorrect = true,
                            QuestionId = 206,
                            Text = "Нет, запрещён"
                        },
                        new
                        {
                            Id = 1041,
                            IsCorrect = false,
                            QuestionId = 206,
                            Text = "Да, если нет поезда"
                        },
                        new
                        {
                            Id = 1042,
                            IsCorrect = false,
                            QuestionId = 206,
                            Text = "Да, если включены аварийные огни"
                        },
                        new
                        {
                            Id = 1043,
                            IsCorrect = true,
                            QuestionId = 207,
                            Text = "Уступить дорогу и обеспечить проезд"
                        },
                        new
                        {
                            Id = 1044,
                            IsCorrect = false,
                            QuestionId = 207,
                            Text = "Продолжать движение без изменений"
                        },
                        new
                        {
                            Id = 1045,
                            IsCorrect = false,
                            QuestionId = 207,
                            Text = "Остановиться посреди полосы"
                        },
                        new
                        {
                            Id = 1046,
                            IsCorrect = true,
                            QuestionId = 208,
                            Text = "Нет, нельзя"
                        },
                        new
                        {
                            Id = 1047,
                            IsCorrect = false,
                            QuestionId = 208,
                            Text = "Да, если нет встречных"
                        },
                        new
                        {
                            Id = 1048,
                            IsCorrect = false,
                            QuestionId = 208,
                            Text = "Да, если спешите"
                        },
                        new
                        {
                            Id = 1049,
                            IsCorrect = true,
                            QuestionId = 209,
                            Text = "Нет, запрещён"
                        },
                        new
                        {
                            Id = 1050,
                            IsCorrect = false,
                            QuestionId = 209,
                            Text = "Да, разрешён всегда"
                        },
                        new
                        {
                            Id = 1051,
                            IsCorrect = false,
                            QuestionId = 209,
                            Text = "Разрешён только днём"
                        });
                });

            modelBuilder.Entity("AutoSchool.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Explanation = "Движение разрешает зелёный сигнал светофора.",
                            Text = "Какой сигнал светофора разрешает движение?",
                            TicketId = 1
                        },
                        new
                        {
                            Id = 102,
                            Explanation = "Жёлтый сигнал запрещает движение, кроме случаев, когда остановка может быть опасной или невозможной.",
                            Text = "Разрешено ли движение на жёлтый сигнал светофора?",
                            TicketId = 1
                        },
                        new
                        {
                            Id = 103,
                            Explanation = "Водитель обязан уступить дорогу транспортным средствам, движущимся по пересекаемой дороге.",
                            Text = "Что означает знак «Уступите дорогу»?",
                            TicketId = 1
                        },
                        new
                        {
                            Id = 104,
                            Explanation = "Если не установлены иные ограничения, в населённом пункте разрешено 60 км/ч.",
                            Text = "Максимальная скорость в населённом пункте, если не указано иное?",
                            TicketId = 1
                        },
                        new
                        {
                            Id = 105,
                            Explanation = "Да, если конструкцией транспортного средства предусмотрены ремни безопасности.",
                            Text = "Должны ли водитель и пассажиры быть пристёгнуты ремнями безопасности?",
                            TicketId = 1
                        },
                        new
                        {
                            Id = 106,
                            Explanation = "Остановка на пешеходном переходе запрещена.",
                            Text = "Разрешена ли остановка на пешеходном переходе?",
                            TicketId = 1
                        },
                        new
                        {
                            Id = 107,
                            Explanation = "Остановка ближе 5 метров перед переходом запрещена.",
                            Text = "Разрешена ли остановка ближе 5 метров перед пешеходным переходом?",
                            TicketId = 1
                        },
                        new
                        {
                            Id = 108,
                            Explanation = "Остановиться нужно перед стоп-линией, не заезжая на неё.",
                            Text = "Как нужно остановиться перед стоп-линией при запрещающем сигнале?",
                            TicketId = 1
                        },
                        new
                        {
                            Id = 201,
                            Explanation = "Знак запрещает въезд транспортных средств в данном направлении.",
                            Text = "Что означает знак «Въезд запрещён»?",
                            TicketId = 2
                        },
                        new
                        {
                            Id = 202,
                            Explanation = "Преимущество имеет транспортное средство, приближающееся справа (правило «помехи справа»).",
                            Text = "Кто имеет преимущество на перекрёстке равнозначных дорог?",
                            TicketId = 2
                        },
                        new
                        {
                            Id = 203,
                            Explanation = "Пользоваться телефоном без устройства hands-free запрещено.",
                            Text = "Разрешено ли пользоваться телефоном без гарнитуры во время движения?",
                            TicketId = 2
                        },
                        new
                        {
                            Id = 204,
                            Explanation = "Водитель обязан иметь водительское удостоверение соответствующей категории.",
                            Text = "Какой документ обязан иметь водитель при управлении транспортным средством?",
                            TicketId = 2
                        },
                        new
                        {
                            Id = 205,
                            Explanation = "Днём должны быть включены дневные ходовые огни или ближний свет фар.",
                            Text = "Что должно быть включено днём для обозначения движущегося транспортного средства?",
                            TicketId = 2
                        },
                        new
                        {
                            Id = 206,
                            Explanation = "Разворот на железнодорожном переезде запрещён.",
                            Text = "Разрешён ли разворот на железнодорожном переезде?",
                            TicketId = 2
                        },
                        new
                        {
                            Id = 207,
                            Explanation = "Нужно уступить дорогу и обеспечить беспрепятственный проезд.",
                            Text = "Как поступить при приближении автомобиля спецслужб с маячком и сиреной?",
                            TicketId = 2
                        },
                        new
                        {
                            Id = 208,
                            Explanation = "Пересечение сплошной линии 1.1 запрещено.",
                            Text = "Можно ли пересекать сплошную линию разметки 1.1?",
                            TicketId = 2
                        },
                        new
                        {
                            Id = 209,
                            Explanation = "Обгон в тоннеле запрещён.",
                            Text = "Разрешён ли обгон в тоннеле?",
                            TicketId = 2
                        });
                });

            modelBuilder.Entity("AutoSchool.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Client"
                        });
                });

            modelBuilder.Entity("AutoSchool.Models.TestAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int?>("SelectedOptionId")
                        .HasColumnType("int");

                    b.Property<int>("TestResultId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SelectedOptionId");

                    b.HasIndex("TestResultId");

                    b.ToTable("TestAnswers");
                });

            modelBuilder.Entity("AutoSchool.Models.TestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("int");

                    b.Property<DateTime>("PassedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WrongAnswers")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.HasIndex("UserId");

                    b.ToTable("TestResults");
                });

            modelBuilder.Entity("AutoSchool.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Билет 1"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Билет 2"
                        });
                });

            modelBuilder.Entity("AutoSchool.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1000,
                            Email = "admin@autoschool.local",
                            FirstName = "Admin",
                            LastName = "System",
                            PasswordHash = "PrP+ZrMeO00Q+nC1ytSccRIpSvauTkdqHEBRVdRaoSE=",
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("AutoSchool.Models.AnswerOption", b =>
                {
                    b.HasOne("AutoSchool.Models.Question", "Question")
                        .WithMany("AnswerOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("AutoSchool.Models.Question", b =>
                {
                    b.HasOne("AutoSchool.Models.Ticket", "Ticket")
                        .WithMany("Questions")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("AutoSchool.Models.TestAnswer", b =>
                {
                    b.HasOne("AutoSchool.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoSchool.Models.AnswerOption", "SelectedOption")
                        .WithMany()
                        .HasForeignKey("SelectedOptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AutoSchool.Models.TestResult", "TestResult")
                        .WithMany("Answers")
                        .HasForeignKey("TestResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("SelectedOption");

                    b.Navigation("TestResult");
                });

            modelBuilder.Entity("AutoSchool.Models.TestResult", b =>
                {
                    b.HasOne("AutoSchool.Models.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoSchool.Models.User", "User")
                        .WithMany("TestResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoSchool.Models.User", b =>
                {
                    b.HasOne("AutoSchool.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AutoSchool.Models.Question", b =>
                {
                    b.Navigation("AnswerOptions");
                });

            modelBuilder.Entity("AutoSchool.Models.TestResult", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("AutoSchool.Models.Ticket", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("AutoSchool.Models.User", b =>
                {
                    b.Navigation("TestResults");
                });
#pragma warning restore 612, 618
        }
    }
}
