// <auto-generated />
using System;
using AutoSchool.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoSchool.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260503210103_AddTopicIdToTickets")]
    partial class AddTopicIdToTickets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutoSchool.Models.AnswerOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("AnswerOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsCorrect = true,
                            QuestionId = 1,
                            Text = "Движение запрещено"
                        },
                        new
                        {
                            Id = 2,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "Можно ехать осторожно"
                        },
                        new
                        {
                            Id = 3,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "Можно ехать только направо"
                        },
                        new
                        {
                            Id = 4,
                            IsCorrect = false,
                            QuestionId = 2,
                            Text = "Да, если нет пешеходов"
                        },
                        new
                        {
                            Id = 5,
                            IsCorrect = true,
                            QuestionId = 2,
                            Text = "Нет, запрещено"
                        },
                        new
                        {
                            Id = 6,
                            IsCorrect = false,
                            QuestionId = 2,
                            Text = "Да, если включен поворотник"
                        },
                        new
                        {
                            Id = 7,
                            IsCorrect = false,
                            QuestionId = 3,
                            Text = "Конец населенного пункта"
                        },
                        new
                        {
                            Id = 8,
                            IsCorrect = true,
                            QuestionId = 3,
                            Text = "Приоритет на перекрестках"
                        },
                        new
                        {
                            Id = 9,
                            IsCorrect = false,
                            QuestionId = 3,
                            Text = "Запрет остановки"
                        },
                        new
                        {
                            Id = 10,
                            IsCorrect = true,
                            QuestionId = 4,
                            Text = "Зелёный"
                        },
                        new
                        {
                            Id = 11,
                            IsCorrect = false,
                            QuestionId = 4,
                            Text = "Красный"
                        },
                        new
                        {
                            Id = 12,
                            IsCorrect = false,
                            QuestionId = 4,
                            Text = "Жёлтый"
                        },
                        new
                        {
                            Id = 13,
                            IsCorrect = true,
                            QuestionId = 5,
                            Text = "Запрещено, кроме случаев когда остановка невозможна"
                        },
                        new
                        {
                            Id = 14,
                            IsCorrect = false,
                            QuestionId = 5,
                            Text = "Разрешено всегда"
                        },
                        new
                        {
                            Id = 15,
                            IsCorrect = false,
                            QuestionId = 5,
                            Text = "Разрешено только направо"
                        },
                        new
                        {
                            Id = 16,
                            IsCorrect = true,
                            QuestionId = 6,
                            Text = "Нужно уступить транспортным средствам на пересекаемой дороге"
                        },
                        new
                        {
                            Id = 17,
                            IsCorrect = false,
                            QuestionId = 6,
                            Text = "Движение запрещено"
                        },
                        new
                        {
                            Id = 18,
                            IsCorrect = false,
                            QuestionId = 6,
                            Text = "Вы на главной дороге"
                        },
                        new
                        {
                            Id = 19,
                            IsCorrect = true,
                            QuestionId = 7,
                            Text = "60 км/ч"
                        },
                        new
                        {
                            Id = 20,
                            IsCorrect = false,
                            QuestionId = 7,
                            Text = "90 км/ч"
                        },
                        new
                        {
                            Id = 21,
                            IsCorrect = false,
                            QuestionId = 7,
                            Text = "40 км/ч"
                        },
                        new
                        {
                            Id = 22,
                            IsCorrect = true,
                            QuestionId = 8,
                            Text = "Да, если предусмотрены конструкцией"
                        },
                        new
                        {
                            Id = 23,
                            IsCorrect = false,
                            QuestionId = 8,
                            Text = "Только водитель"
                        },
                        new
                        {
                            Id = 24,
                            IsCorrect = false,
                            QuestionId = 8,
                            Text = "Только на трассе"
                        },
                        new
                        {
                            Id = 25,
                            IsCorrect = true,
                            QuestionId = 9,
                            Text = "Нет, запрещена"
                        },
                        new
                        {
                            Id = 26,
                            IsCorrect = false,
                            QuestionId = 9,
                            Text = "Да, если нет пешеходов"
                        },
                        new
                        {
                            Id = 27,
                            IsCorrect = false,
                            QuestionId = 9,
                            Text = "Да, не более 1 минуты"
                        },
                        new
                        {
                            Id = 28,
                            IsCorrect = true,
                            QuestionId = 10,
                            Text = "Да, запрещена"
                        },
                        new
                        {
                            Id = 29,
                            IsCorrect = false,
                            QuestionId = 10,
                            Text = "Нет, разрешена"
                        },
                        new
                        {
                            Id = 30,
                            IsCorrect = false,
                            QuestionId = 10,
                            Text = "Запрещена только после перехода"
                        },
                        new
                        {
                            Id = 31,
                            IsCorrect = true,
                            QuestionId = 11,
                            Text = "Перед стоп-линией"
                        },
                        new
                        {
                            Id = 32,
                            IsCorrect = false,
                            QuestionId = 11,
                            Text = "На стоп-линии"
                        },
                        new
                        {
                            Id = 33,
                            IsCorrect = false,
                            QuestionId = 11,
                            Text = "После стоп-линии"
                        },
                        new
                        {
                            Id = 34,
                            IsCorrect = true,
                            QuestionId = 12,
                            Text = "Въезд запрещён в данном направлении"
                        },
                        new
                        {
                            Id = 35,
                            IsCorrect = false,
                            QuestionId = 12,
                            Text = "Движение запрещено для всех"
                        },
                        new
                        {
                            Id = 36,
                            IsCorrect = false,
                            QuestionId = 12,
                            Text = "Остановка запрещена"
                        },
                        new
                        {
                            Id = 37,
                            IsCorrect = true,
                            QuestionId = 13,
                            Text = "Транспортное средство справа"
                        },
                        new
                        {
                            Id = 38,
                            IsCorrect = false,
                            QuestionId = 13,
                            Text = "Транспортное средство слева"
                        },
                        new
                        {
                            Id = 39,
                            IsCorrect = false,
                            QuestionId = 13,
                            Text = "Тот, кто едет быстрее"
                        },
                        new
                        {
                            Id = 40,
                            IsCorrect = true,
                            QuestionId = 14,
                            Text = "Запрещено"
                        },
                        new
                        {
                            Id = 41,
                            IsCorrect = false,
                            QuestionId = 14,
                            Text = "Разрешено"
                        },
                        new
                        {
                            Id = 42,
                            IsCorrect = false,
                            QuestionId = 14,
                            Text = "Разрешено только в пробке"
                        },
                        new
                        {
                            Id = 43,
                            IsCorrect = true,
                            QuestionId = 15,
                            Text = "Водительское удостоверение соответствующей категории"
                        },
                        new
                        {
                            Id = 44,
                            IsCorrect = false,
                            QuestionId = 15,
                            Text = "Паспорт"
                        },
                        new
                        {
                            Id = 45,
                            IsCorrect = false,
                            QuestionId = 15,
                            Text = "Свидетельство о рождении"
                        },
                        new
                        {
                            Id = 46,
                            IsCorrect = true,
                            QuestionId = 16,
                            Text = "ДХО или ближний свет фар"
                        },
                        new
                        {
                            Id = 47,
                            IsCorrect = false,
                            QuestionId = 16,
                            Text = "Только дальний свет"
                        },
                        new
                        {
                            Id = 48,
                            IsCorrect = false,
                            QuestionId = 16,
                            Text = "Только противотуманные фары"
                        },
                        new
                        {
                            Id = 49,
                            IsCorrect = true,
                            QuestionId = 17,
                            Text = "Нет, запрещён"
                        },
                        new
                        {
                            Id = 50,
                            IsCorrect = false,
                            QuestionId = 17,
                            Text = "Да, если нет поезда"
                        },
                        new
                        {
                            Id = 51,
                            IsCorrect = false,
                            QuestionId = 17,
                            Text = "Да, если включены аварийные огни"
                        },
                        new
                        {
                            Id = 52,
                            IsCorrect = true,
                            QuestionId = 18,
                            Text = "Уступить дорогу и обеспечить проезд"
                        },
                        new
                        {
                            Id = 53,
                            IsCorrect = false,
                            QuestionId = 18,
                            Text = "Продолжать движение без изменений"
                        },
                        new
                        {
                            Id = 54,
                            IsCorrect = false,
                            QuestionId = 18,
                            Text = "Остановиться посреди полосы"
                        },
                        new
                        {
                            Id = 55,
                            IsCorrect = true,
                            QuestionId = 19,
                            Text = "Нет, нельзя"
                        },
                        new
                        {
                            Id = 56,
                            IsCorrect = false,
                            QuestionId = 19,
                            Text = "Да, если нет встречных"
                        },
                        new
                        {
                            Id = 57,
                            IsCorrect = false,
                            QuestionId = 19,
                            Text = "Да, если спешите"
                        },
                        new
                        {
                            Id = 58,
                            IsCorrect = true,
                            QuestionId = 20,
                            Text = "Нет, запрещён"
                        },
                        new
                        {
                            Id = 59,
                            IsCorrect = false,
                            QuestionId = 20,
                            Text = "Да, разрешён всегда"
                        },
                        new
                        {
                            Id = 60,
                            IsCorrect = false,
                            QuestionId = 20,
                            Text = "Разрешён только днём"
                        });
                });

            modelBuilder.Entity("AutoSchool.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Transmission")
                        .HasColumnType("int");

                    b.Property<string>("VehicleBrand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "petrov@autoschool.local",
                            FirstName = "Иван",
                            LastName = "Петров",
                            Phone = "+7 900 111-22-33",
                            Transmission = 1,
                            VehicleBrand = "Lada",
                            VehicleCategory = "B",
                            VehicleModel = "Vesta"
                        },
                        new
                        {
                            Id = 2,
                            Email = "smirnova@autoschool.local",
                            FirstName = "Анна",
                            LastName = "Смирнова",
                            Phone = "+7 900 222-33-44",
                            Transmission = 2,
                            VehicleBrand = "Kia",
                            VehicleCategory = "B",
                            VehicleModel = "Rio"
                        },
                        new
                        {
                            Id = 3,
                            Email = "kuznetsov@autoschool.local",
                            FirstName = "Сергей",
                            LastName = "Кузнецов",
                            Phone = "+7 900 333-44-55",
                            Transmission = 1,
                            VehicleBrand = "Yamaha",
                            VehicleCategory = "A",
                            VehicleModel = "MT-07"
                        });
                });

            modelBuilder.Entity("AutoSchool.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<int>("TopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.HasIndex("TopicId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Explanation = "Красный сигнал запрещает движение.",
                            Text = "Что означает красный сигнал светофора?",
                            TicketId = 1,
                            TopicId = 2
                        },
                        new
                        {
                            Id = 2,
                            Explanation = "Обгон на пешеходном переходе запрещен.",
                            Text = "Можно ли выполнять обгон на пешеходном переходе?",
                            TicketId = 1,
                            TopicId = 5
                        },
                        new
                        {
                            Id = 4,
                            Explanation = "Движение разрешает зелёный сигнал светофора.",
                            Text = "Какой сигнал светофора разрешает движение?",
                            TicketId = 1,
                            TopicId = 2
                        },
                        new
                        {
                            Id = 5,
                            Explanation = "Жёлтый сигнал запрещает движение, кроме случаев, когда остановка может быть опасной или невозможной.",
                            Text = "Разрешено ли движение на жёлтый сигнал светофора?",
                            TicketId = 1,
                            TopicId = 2
                        },
                        new
                        {
                            Id = 6,
                            Explanation = "Водитель обязан уступить дорогу транспортным средствам, движущимся по пересекаемой дороге.",
                            Text = "Что означает знак «Уступите дорогу»?",
                            TicketId = 1,
                            TopicId = 3
                        },
                        new
                        {
                            Id = 7,
                            Explanation = "Если не установлены иные ограничения, в населённом пункте разрешено 60 км/ч.",
                            Text = "Максимальная скорость в населённом пункте, если не указано иное?",
                            TicketId = 1,
                            TopicId = 4
                        },
                        new
                        {
                            Id = 8,
                            Explanation = "Да, если конструкцией транспортного средства предусмотрены ремни безопасности.",
                            Text = "Должны ли водитель и пассажиры быть пристёгнуты ремнями безопасности?",
                            TicketId = 1,
                            TopicId = 1
                        },
                        new
                        {
                            Id = 9,
                            Explanation = "Остановка на пешеходном переходе запрещена.",
                            Text = "Разрешена ли остановка на пешеходном переходе?",
                            TicketId = 1,
                            TopicId = 6
                        },
                        new
                        {
                            Id = 10,
                            Explanation = "Остановка ближе 5 метров перед переходом запрещена.",
                            Text = "Разрешена ли остановка ближе 5 метров перед пешеходным переходом?",
                            TicketId = 1,
                            TopicId = 6
                        },
                        new
                        {
                            Id = 11,
                            Explanation = "Остановиться нужно перед стоп-линией, не заезжая на неё.",
                            Text = "Где нужно остановиться перед стоп-линией при запрещающем сигнале?",
                            TicketId = 1,
                            TopicId = 2
                        },
                        new
                        {
                            Id = 3,
                            Explanation = "Он указывает, что водитель находится на главной дороге.",
                            Text = "Что означает знак 'Главная дорога'?",
                            TicketId = 2,
                            TopicId = 3
                        },
                        new
                        {
                            Id = 12,
                            Explanation = "Знак запрещает въезд транспортных средств в данном направлении.",
                            Text = "Что означает знак «Въезд запрещён»?",
                            TicketId = 2,
                            TopicId = 3
                        },
                        new
                        {
                            Id = 13,
                            Explanation = "Преимущество имеет транспортное средство, приближающееся справа (правило «помехи справа»).",
                            Text = "Кто имеет преимущество на перекрёстке равнозначных дорог?",
                            TicketId = 2,
                            TopicId = 1
                        },
                        new
                        {
                            Id = 14,
                            Explanation = "Пользоваться телефоном без устройства hands-free запрещено.",
                            Text = "Разрешено ли пользоваться телефоном без гарнитуры во время движения?",
                            TicketId = 2,
                            TopicId = 1
                        },
                        new
                        {
                            Id = 15,
                            Explanation = "Водитель обязан иметь водительское удостоверение соответствующей категории.",
                            Text = "Какой документ обязан иметь водитель при управлении транспортным средством?",
                            TicketId = 2,
                            TopicId = 1
                        },
                        new
                        {
                            Id = 16,
                            Explanation = "Днём должны быть включены дневные ходовые огни или ближний свет фар.",
                            Text = "Что должно быть включено днём для обозначения движущегося транспортного средства?",
                            TicketId = 2,
                            TopicId = 1
                        },
                        new
                        {
                            Id = 17,
                            Explanation = "Разворот на железнодорожном переезде запрещён.",
                            Text = "Разрешён ли разворот на железнодорожном переезде?",
                            TicketId = 2,
                            TopicId = 7
                        },
                        new
                        {
                            Id = 18,
                            Explanation = "Нужно уступить дорогу и обеспечить беспрепятственный проезд.",
                            Text = "Как поступить при приближении автомобиля спецслужб с маячком и сиреной?",
                            TicketId = 2,
                            TopicId = 7
                        },
                        new
                        {
                            Id = 19,
                            Explanation = "Пересечение сплошной линии 1.1 запрещено.",
                            Text = "Можно ли пересекать сплошную линию разметки 1.1?",
                            TicketId = 2,
                            TopicId = 1
                        },
                        new
                        {
                            Id = 20,
                            Explanation = "Обгон в тоннеле запрещён.",
                            Text = "Разрешён ли обгон в тоннеле?",
                            TicketId = 2,
                            TopicId = 5
                        });
                });

            modelBuilder.Entity("AutoSchool.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Client"
                        });
                });

            modelBuilder.Entity("AutoSchool.Models.TestAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int?>("SelectedOptionId")
                        .HasColumnType("int");

                    b.Property<int>("TestResultId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SelectedOptionId");

                    b.HasIndex("TestResultId");

                    b.ToTable("TestAnswers");
                });

            modelBuilder.Entity("AutoSchool.Models.TestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("int");

                    b.Property<DateTime>("PassedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TicketId")
                        .HasColumnType("int");

                    b.Property<int?>("TopicId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WrongAnswers")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.HasIndex("TopicId");

                    b.HasIndex("UserId");

                    b.ToTable("TestResults");
                });

            modelBuilder.Entity("AutoSchool.Models.TheoryCredit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PlannedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TopicId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.HasIndex("UserId");

                    b.ToTable("TheoryCredits");
                });

            modelBuilder.Entity("AutoSchool.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Билет 1",
                            TopicId = 1
                        },
                        new
                        {
                            Id = 2,
                            Title = "Билет 2",
                            TopicId = 1
                        });
                });

            modelBuilder.Entity("AutoSchool.Models.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Общее"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Светофор и регулировщик"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Дорожные знаки"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Скорость"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Обгон и опережение"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Остановка и стоянка"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Переезды и спецсигналы"
                        });
                });

            modelBuilder.Entity("AutoSchool.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TrainingPlannedEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TrainingStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("InstructorId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1000,
                            Email = "admin@autoschool.local",
                            FirstName = "Admin",
                            LastName = "System",
                            PasswordHash = "PrP+ZrMeO00Q+nC1ytSccRIpSvauTkdqHEBRVdRaoSE=",
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("AutoSchool.Models.AnswerOption", b =>
                {
                    b.HasOne("AutoSchool.Models.Question", "Question")
                        .WithMany("AnswerOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("AutoSchool.Models.Question", b =>
                {
                    b.HasOne("AutoSchool.Models.Ticket", "Ticket")
                        .WithMany("Questions")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoSchool.Models.Topic", "Topic")
                        .WithMany("Questions")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("AutoSchool.Models.TestAnswer", b =>
                {
                    b.HasOne("AutoSchool.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoSchool.Models.AnswerOption", "SelectedOption")
                        .WithMany()
                        .HasForeignKey("SelectedOptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AutoSchool.Models.TestResult", "TestResult")
                        .WithMany("Answers")
                        .HasForeignKey("TestResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("SelectedOption");

                    b.Navigation("TestResult");
                });

            modelBuilder.Entity("AutoSchool.Models.TestResult", b =>
                {
                    b.HasOne("AutoSchool.Models.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId");

                    b.HasOne("AutoSchool.Models.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId");

                    b.HasOne("AutoSchool.Models.User", "User")
                        .WithMany("TestResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");

                    b.Navigation("Topic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoSchool.Models.TheoryCredit", b =>
                {
                    b.HasOne("AutoSchool.Models.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AutoSchool.Models.User", "User")
                        .WithMany("TheoryCredits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoSchool.Models.Ticket", b =>
                {
                    b.HasOne("AutoSchool.Models.Topic", "Topic")
                        .WithMany("Tickets")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("AutoSchool.Models.User", b =>
                {
                    b.HasOne("AutoSchool.Models.Instructor", "Instructor")
                        .WithMany("Users")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AutoSchool.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AutoSchool.Models.Instructor", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("AutoSchool.Models.Question", b =>
                {
                    b.Navigation("AnswerOptions");
                });

            modelBuilder.Entity("AutoSchool.Models.TestResult", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("AutoSchool.Models.Ticket", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("AutoSchool.Models.Topic", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("AutoSchool.Models.User", b =>
                {
                    b.Navigation("TestResults");

                    b.Navigation("TheoryCredits");
                });
#pragma warning restore 612, 618
        }
    }
}
